FROM python:3.10-slim-bullseye as python-packages-builder

COPY requirements.api_server.txt  ./requirements.txt
RUN  pip install -r requirements.txt

FROM python:3.10-slim-bullseye as runtime
COPY --from=python-packages-builder /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages

WORKDIR /app
EXPOSE 80
COPY ${TOKENIZER_PATH} ./tokenizer
COPY ${MODEL_PATH} ./model
COPY src/ ./
