repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=50000"] # 50 MB
      - id: check-json
      - id: check-toml
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
  - repo: local
    hooks:
      - id: terraform_fmt
        language: system
        name: terraform_fmt
        entry: terraform fmt terraform
        pass_filenames: false
        always_run: true
