FROM python:3.10-slim-bullseye as python-packages-builder

COPY requirements.txt  ./requirements.txt
RUN pip install --user -r requirements.txt

FROM python:3.10-slim-bullseye as runtime
WORKDIR /app

ARG MODEL_PATH
ARG TOKENIZER_PATH

EXPOSE 8080
COPY ${TOKENIZER_PATH} ./tokenizer
COPY ${MODEL_PATH} ./model
COPY --from=python-packages-builder /root/.local /root/.local
COPY src/ .
ENTRYPOINT [ "python", "-m", "gunicorn", "main:app", "--workers", "8", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8080", "-p"]